variables:
  DOCKER_HOST: unix:///var/run/docker.sock
  DOCKER_DRIVER: overlay2

image:
  name: docker/compose:1.29.2

services:
  - name: docker:dind
    alias: docker

stages:
  - build
  - deploy
  - cleanup

before_script:
  - docker version
  - docker-compose version

build_analytics:
  stage: build
  script:
    - echo "DEMO build"
    - docker-compose -f docker-compose.prod.yml down
    - docker-compose -f docker-compose.prod.yml build
  only:
    - main
  tags:
    - oaipmh

deploy_analytics:
  stage: deploy
  script:
    - echo "DEMO deploy"
    - docker-compose -f docker-compose.prod.yml up -d
  only:
    - main
  tags:
    - oaipmh

cleanup_analytics:
  stage: cleanup
  script:
    - echo "Cleaning up the system"
    - docker system prune -a --volumes -f
  only:
    - main
  tags:
    - oaipmh
  when: manual
