version: '3.9'
services:
  aoe-etl-processor:
    build:
      context: .
      dockerfile: ./service-etl-processor/Dockerfile
    image: aoe-etl-processor:latest
    container_name: aoe-etl-processor
    restart: unless-stopped
    ports:
      - '8080:8080'
    env_file:
      - /environment/aoe-data-analytics/.env
    logging:
      options:
        max-size: '10m'
        max-file: '3'
    networks:
      - network-etl-processor

networks:
  network-etl-processor:
    driver: bridge
