logging:
  level:
    org.apache.kafka: INFO
    org.springframework: ERROR
server:
  port:
  servlet:
    context-path: /api
spring:
  data:
    mongodb:
      database:
      host:
      port:
      password:
      username:
  kafka:
    consumer:
      # multiple servers comma separated "host:9092,host:9093"
      bootstrap-servers:
      group-id:
      auto-offset-reset: latest
      enable-auto-commit: true
    producer:
      batch-size: 10
      client-id:
      bootstrap-servers:
